name: Check licenses in source files

on:
  workflow_dispatch:
  workflow_call:
  push:
  pull_request:
    branches:
      - main

jobs:
  check-spdx-headers:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: enarx/spdx@master
      with:
        licenses: |-
          Apache-2.0